name: flutter_meteor
description: This library make connection between meteor backend and flutter app easily. Design to work seamlessly with StreamBuilder and FutureBuilder.
version: 1.2.0
homepage: https://github.com/tanutapi/dart_meteor

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^2.1.5
  rxdart: ^0.24.1
  shared_preferences: ^0.5.8
  universal_io: ^1.0.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
